"""empty message

Revision ID: 3e3dd1111c6f
Revises: 
Create Date: 2020-08-19 17:05:44.792479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3dd1111c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_record_ibfk_1', 'change_record', type_='foreignkey')
    op.drop_constraint('customers_ibfk_1', 'customers', type_='foreignkey')
    op.drop_constraint('identifiers_ibfk_1', 'identifiers', type_='foreignkey')
    op.drop_constraint('iids_ibfk_1', 'iids', type_='foreignkey')
    op.drop_constraint('iids_ibfk_2', 'iids', type_='foreignkey')
    op.drop_constraint('productions_ibfk_1', 'productions', type_='foreignkey')
    op.drop_constraint('productions_ibfk_2', 'productions', type_='foreignkey')
    op.drop_constraint('pt_is_ibfk_2', 'pt_is', type_='foreignkey')
    op.drop_constraint('pt_is_ibfk_1', 'pt_is', type_='foreignkey')
    op.drop_constraint('repair_records_ibfk_1', 'repair_records', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('repair_records_ibfk_1', 'repair_records', 'productions', ['production_id'], ['id'])
    op.create_foreign_key('pt_is_ibfk_1', 'pt_is', 'identifiers', ['identifier_id'], ['id'])
    op.create_foreign_key('pt_is_ibfk_2', 'pt_is', 'product_types', ['product_type_id'], ['id'])
    op.create_foreign_key('productions_ibfk_2', 'productions', 'product_types', ['product_type_id'], ['id'])
    op.create_foreign_key('productions_ibfk_1', 'productions', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('iids_ibfk_2', 'iids', 'identifiers', ['identifier_id'], ['id'])
    op.create_foreign_key('iids_ibfk_1', 'iids', 'productions', ['production_id'], ['id'])
    op.create_foreign_key('identifiers_ibfk_1', 'identifiers', 'identifier_types', ['identifier_type_id'], ['id'])
    op.create_foreign_key('customers_ibfk_1', 'customers', 'adress', ['adress_id'], ['id'])
    op.create_foreign_key('change_record_ibfk_1', 'change_record', 'users', ['change_userid'], ['id'])
    # ### end Alembic commands ###
